name: Run gradle build

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - uses: qupath/actions/.github/workflows/gradle.yml@main
